# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_demoinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('Feature_A_title', models.CharField(max_length=20)),
                ('Feature_A_data', models.CharField(max_length=100)),
                ('Feature_B_title', models.CharField(max_length=20)),
                ('Feature_B_data', models.CharField(max_length=100)),
                ('Feature_C_title', models.CharField(max_length=20)),
                ('Feature_C_data', models.CharField(max_length=100)),
                ('image_paths', models.CharField(max_length=200)),
            ],
        ),
    ]
