# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tools_site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(max_length=200)),
                ('site_info', models.CharField(max_length=200)),
                ('site_title', models.CharField(max_length=200)),
                ('site_type', models.CharField(max_length=2560)),
                ('image_paths', models.CharField(max_length=200)),
            ],
        ),
    ]
